### ISSUE TITLE
microsoft.graph client only pulls 10 emails

### ISSUE THREAD

**Issue by twcarnahan** [microsoftgraph/aspnet-snippets-sample#12]
Maybe I'm just missing something on this but with the snippet /Mail/GetMyInboxMessages, it only brings back 10 records; if you can point to the answer here I would appreciate it. 

Thank you for the snippets sample as it is very informative, 
Vr, Tim:

**Comment by DianeD** [comment]
Hi Tim. That looks like the default paging size. The response includes an **odata.nextLink** for the paged data. This is the raw response:

```
{
  "@odata.context":"https://graph.microsoft.com/v1.0/$metadata#users('<user-id>')/messages",
  "@odata.nextLink":"https://graph.microsoft.com/v1.0/me/messages?$skip=10",
  "value":[...]
}
```

In the SDK, the returned messages collection has a **NextPageRequest** property (with the **skip** parameter in its **QueryOptions** property). The sample doesn't handle paging, but you can use the **NextPageRequest** property to query for all the results you want. Or if you want to customize paging behavior, you can use the [**top** and **skip** parameters](https://graph.microsoft.io/en-us/docs/overview/query_parameters).

I don't see the default page size documented in the [API docs](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/user_list_messages), but will work on getting it added. Thanks!
