### ISSUE TITLE
Get Attachment from Outlook using the HasAttachment Bool?

### ISSUE THREAD

**Issue by twcarnahan** [microsoftgraph/aspnet-snippets-sample#13]
While attempting to get the attachment from Outlook, I have a problem using the message.hasattachement while checking to see which message has an attachment before getting the attachment; can you show example or further your example getting an attachment.
This works from the graph.microsoft.io
https://graph.microsoft.com/v1.0/me/MailFolders/Inbox/Messages?$select=webLink,subject,hasAttachments just can't get it into the Razor page --- ;(

added behavior notes:
a and b below work using the tool at graph.microsoft.io using a message with one attachment
a) //graph.microsoft.com/v1.0/me/mailFolders/inbox/messages/[message.id]/attachments?$select=name,size
b) //graph.microsoft.com/v1.0/me/mailFolders/inbox/messages/[message.id]/attachments/$count
the below seems to work and downloads to the page without the page having the capability to view so it's blank - or at least I didn't get an error.
c) //graph.microsoft.com/v1.0/me/mailFolders/inbox/messages/[message.id]/attachments
===
My problem exist while using the razor and "results", I'm trying to get that page to show "getmessage" the attachment (I've added gif for this) and then click the link (attachment name) which I have successfully got to the __ResultsPartial.cshtml page. 
I had to use the below:
IMessageAttachmentsCollectionPage attachments = await graphClient.Me.Messages[message.Id].Attachments.Request().Select("Name,Size").GetAsync();

This is all a bit messy and any direction would be appreciated :)
Vr, Tim:
graph.microsoft.io

**Comment by DianeD** [comment]
Hi Tim. This sample uses the Graph SDK, so the equivalent request is this:

`IMailFolderMessagesCollectionPage messages = await graphClient.Me.MailFolders.Inbox.Messages.Request().Select("webLink,subject,hasAttachments").GetAsync();`

You can use **Expand** to retrieve attachments in the same request:

`IMailFolderMessagesCollectionPage messages = await graphClient.Me.MailFolders.Inbox.Messages.Request().Select("webLink,subject,hasAttachments").Expand("attachments").GetAsync();`

What is it that you're trying to get into the Razor page? Are you extending this sample app to show attachment data?

**Comment by DianeD** [comment]
Sorry, I didn't see your additional info until I refreshed the page. The sample isn't currently designed to show binary results. To indicate successful file download, it displays some stream info, like in this example that shows the stream size:

```
        public async Task<ActionResult> GetMyInboxMessagesThatHaveAttachments()
        {
            ResultsViewModel results = new ResultsViewModel();
            List<ResultsItem> items = new List<ResultsItem>();

            try
            {

                // Initialize the GraphServiceClient.
                GraphServiceClient graphClient = SDKHelper.GetAuthenticatedClient();

                // Get messages in the Inbox folder.
                IMailFolderMessagesCollectionPage messages = await graphClient.Me.MailFolders.Inbox.Messages.Request().Filter("hasAttachments eq true").Expand("attachments").GetAsync();
                
                if (messages?.Count > 0)
                {
                    foreach (Message message in messages)
                    {
                        items.Add(new ResultsItem
                        {
                            Display = message.Subject,
                            Id = message.Id,
                            Properties = new Dictionary<string, object>
                            {
                                { "Attachment count", message.Attachments.Count },
                                { "First attachment name", message.Attachments[0].Name },
                                { "First attachment type", message.Attachments[0].ODataType },
                                { "First attachment size", message.Attachments[0].Size }
                            }
                        });
                    }
                }
                results.Items = items;
            }
            catch (ServiceException se)
            {
                if (se.Error.Message == Resource.Error_AuthChallengeNeeded) return new EmptyResult();

                // Personal accounts that aren't enabled for the Outlook REST API get a "MailboxNotEnabledForRESTAPI" or "MailboxNotSupportedForRESTAPI" error.
                return RedirectToAction("Index", "Error", new { message = string.Format(Resource.Error_Message, Request.RawUrl, se.Error.Code, se.Error.Message) });
            }
            return View("Test", results);
        }
```

**Comment by twcarnahan** [comment]
Diane,


1. Thanks for your clarity - on the "Expand" functionality with IMailFolderMessageCollectionPage, - I can't get the message.attachments.Name or .Size as it states an ERROR with IMessageAttachmentsCollectionPage.

NOTE: I tried using the IMailFolderMessageCollectionPage " IMailFolderMessagesCollectionPage messages = await graphClient.Me.MailFolders.Inbox.Messages.Request().Select("webLink,subject,hasAttachments").Expand("attachments").Select("Name,Size").GetAsync();".


I don't think this works -- or I just missed something?

===

About my overall goal,

I was expanding this to show messages that could be selected to be put into our CRM with Attachments. So, with using two statements, I do get all the elements on the Razor Page, but wanted to used the "attachment.name" in a link on the Razor page that opened the file in question; this is where I'm stuck regardless if I can get the IMailFolderMessageCollectionPage to retrieve all items.


Vr, Tim:


________________________________

**Comment by twcarnahan** [comment]
Diane,

I set my variables per below and do not use the "properties" as I want the results to show whether there is an attachment per email before you click "getmymessage"
        // The ID and display name for the entity's radio button.
        public string Id { get; set; }
        public string Display { get; set; }
        public bool? HasAttachment { get; internal set; }
        public string EmailAttachmentName { get; internal set; }
        public int? EmailAttachmentSize { get; internal set; }
From using both IMailFolderMessageCollectionPage and IMessageAttachmentCollectionPage the above works.
I'm only trying to get a "download" link for the actual attachment; I use the paperclip.gif with "HasAttachement" and if there were several attachments, there would be a paperclip per attachment. The img title="@item.EmailAttachmentName".[cid:e6bf9d4e-c5ba-4789-9073-0ec5328ad135]


My problem is that I can't pull the actual file from graph to the razor page.

Much appreciated in pointing me in the right direction.
Tim:
________________________________

**Comment by twcarnahan** [comment]
Opps see 7:53 PM message below: I put the wrong line that I was trying and it didn't work because there were two select request; the below works but does not provide attachments.name, attachments.size - I believe it provides the file but that comes in from a stream and I don't know how to capture that other than put it in a database or to the file system.

IMailFolderMessagesCollectionPage messages = await graphClient.Me.MailFolders.Inbox.Messages.Request().Select("webLink,subject,hasAttachments").Expand("attachments").GetAsync();


________________________________

**Comment by DianeD** [comment]
Hi Tim. The attachment name and size should be on the items in the attachments collection, for example: `message.Attachments[0].Name`

I'm getting the stream too, but the **ContentLocation** property is null. This sounds like what you're looking for. I'll try to find out how to get it.

>contentLocation:  The Uniform Resource Identifier (URI) that corresponds to the location of the content of the attachment.

**Comment by twcarnahan** [comment]
Diane,


Your right!

The below does work:

IMailFolderMessagesCollectionPage messages = await graphClient.Me.MailFolders.Inbox.Messages.Request().Select("webLink,subject,hasAttachments").Expand("attachments").GetAsync();


NOTE:

About "embedded" attachments message.attachments[0].IsInLine,  the "HasAttachments" = false is set while there are embedded attachments.  I don't know how to "test" for this scenario and don't know if graph should set the "HasAttachments" = true or make that item part of the IMailFolderMessageCollectionPage for example HasEmbeddedAttachements which is similar to HasAttachments; otherwise this may be an orphan item or unreachable unless you have an attachment.


I need to take a brake [😊]

I thought this was simple but it's a bit more complex.

Thank you for your direction with Microsoft Graph!!!

All is appreciated, Tim:




________________________________

**Comment by twcarnahan** [comment]
Diane,


I've found that creating the message list with GetMyInboxMessages using the "Expand" option downloads all the files in the graph query.

This is very expensive and the only real gain is having to know how many attachments there are each email; adding "AttachmentCount" like "HasAttachments" would be nice.


About the embedded attachments, this is ok in the way it works today because, you can immediately find this out when you open the message in question, but again adding it would be nice.


using the "filter" and not allowing the "stream" to be apart of the "Expand" function would make this work very well too but you can only have one "Select" statement and it has to be reference of the Object being used not the "Expand" Object. (if I said that right)


To continue on this expanding your snippet, (which I've learned much - thank you)

Any news on ContentLocation?


again, thank you for your snippets and direction, Tim:


________________________________

**Comment by DianeD** [comment]
Hi Tim. No news on ContentLocation yet.

I did confirm that it's by design that **hasAttachments** does not apply to inline attachments. I also learned this: If the message has inline attachments, they're indicated in the HTML of the message's **content** property with a **src** attribute like: `src=\"cid:image001.jpg@01D26CD8.6C05F070\`

To avoid a single expensive request, you could send requests to the `messages/{id}/attachments` endpoint (like in your first comment) as needed. Then you could select the attachment properties you want.

**Comment by twcarnahan** [comment]
Diane,

Thank you for the definitive on IsInLine - I sort of was getting to that answer "trial and error".


Trying to wrap up this today - just need to put the stream in a blob field in SQL table as this would be my "ContentLocation" [😊]


A side note:

1) I'm not sure how to "close" the question so it doesn't stay open?

2) I don't know why my text is so large in my question either - any direction on these issues would be beneficial.


13 Friday 2017

Have a great day, Tim:


________________________________

**Comment by twcarnahan** [comment]
Diane,

What item are you getting the stream?


Thank you much, Tim:

________________________________

**Comment by twcarnahan** [comment]
Diane,


I'm trying many different ways but can't get the stream -

I noticed you have an added file.AdditionalData["@microsoft.graph.downloadUrl"] parameter while working with files in the FilesService.cs DownloadFile method line 194.

So, while using the  Message message = await graphClient.Me.Messages[id].Request().Expand("attachments").GetAsync();

Do I need to use the below from FilesService.cs?

  // Get the file content.
                using (Stream stream = await graphClient.Me.Drive.Items[id].Content.Request().GetAsync())

if so, I'm just guessing now [😊]

Anything you can provide to help is appreciated.


Tim:

________________________________

**Comment by twcarnahan** [comment]
Diane,


I'm struggling to find how you get attachment.ContentBytes as it is not an option or gives me an error attachment does not contain "ContentBytes.

I'm using Message message = await graphClient.Me.Messages[id].Request().Expand("attachments").GetAsync();

===

Really appreciate if you could give me a hint on where this is as everything else is there but this.


Much appreciated, Tim:

________________________________

**Comment by DianeD** [comment]
Hi Tim. I could see the ContentBytes property in the local variable, but I had to cast it as a FileAttachment in order to access it. For example: 
```
IMessageAttachmentsCollectionPage attachments = await graphClient.Me.Messages[message.Id].Attachments.Request().GetAsync();
foreach (Attachment attachment in attachments)
{
    if (attachment.ODataType == "#microsoft.graph.fileAttachment")
    {
        FileAttachment fileAttachment = attachment as FileAttachment;
        byte[] contentBytes = fileAttachment.ContentBytes;
    }
}
```

Note I'm querying the Attachments endpoint directly, which is differs from your previous example.

I added the check for attachment type because only attachments of type [FileAttachment](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/resources/fileattachment) have the ContentBytes property. This includes FileAttachments that are inline.

I'll check whether this is expected behavior (the explicit cast).

**Comment by twcarnahan** [comment]
Diane,


This works -- your right again --- you have to get the attachment into a different CollectionPage for it to have the property of ContentBytes. (not sure if I said that correctly)


Ok --- I'm going to clean up some things and I think it would be valuable knowledge to put this in your "snippets" or the documentation.


Have the best rest of TGIF the "13th", Tim:

Diane, I very much appreciate your knowledge, time and direction!!!

Tim:

________________________________
