### ISSUE TITLE
Application is not supported by this api version.

### ISSUE THREAD

**Issue by yfan183** [microsoftgraph/aspnet-snippets-sample#16]
When just running the sample itself it says Application is not supported by this api version. But my application is registered in Azure portal which supposedly uses the v1.0 endpoint

**Comment by DianeD** [comment]
Hi @yfan183 . This sample uses the Azure AD v2.0 endpoint and needs to be registered on the [Microsoft Application Registration Portal](https://apps.dev.microsoft.com). If this isn't the portal you used, can you try registering the sample there?

**Comment by DianeD** [comment]
Hi @yfan183 . Please reopen this if you're still having problems.
