### ISSUE TITLE
4MB total size of each REST request 

### ISSUE THREAD

**Issue by twcarnahan** [microsoftgraph/aspnet-snippets-sample#18]
https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/message_post_attachments
Since there is currently a limit of 4MB on the total size of each REST request, this limits the size of the attachment you can add to under 4MB.

**Comment by twcarnahan** [comment]
I just found this tiny bit of information out --- this makes graph useless for attachments --- Is there a way to change this or work around this? 

Much appreciated, Tim:

**Comment by twcarnahan** [comment]
Can you ask if going through the effort creating an Outlook REST endpoint, would that have any conflicts with using "Microsoft.Graph" library; I guess the library Microsoft.Office365.OutlookServices-V2.0. 
Is this the preferred solution when you want to use the "Send" functionality? 
From reading, they seem so similar this is why I ask if I could just switch the REST endpoint for graph because it uses the same Token?
Much appreciate your concern and help with this direction on microsoftgraph concepts, Tim:

**Comment by DianeD** [comment]
Hi Tim. As you noted, the Microsoft Graph currently has a 4MB limit. If you need to send larger file attachments, you could use the Outlook REST API, which has a limit of 150MB. I'm not very familiar with Outlook development but [this tutorial](https://dev.outlook.com/restapi/tutorial/dotnet) should help. If your scenario depends on sending larger attachments and you're only using Outlook services, this might be your best option for now.

If you want to use both the Outlook REST endpoint and the Microsoft Graph endpoint, they require different access tokens so you'd need to obtain them separately.

If you want to use Microsoft Graph only, one workaround is to upload the file to OneDrive and then provide a sharing link in the message. Here's a [UploadLargeFile C#/UWP snippet](https://github.com/microsoftgraph/uwp-csharp-snippets-sample/blob/master/Microsoft-Graph-Snippets-SDK/Users/UserSnippets.cs#L24) that you can base your file-upload method on.

**Comment by twcarnahan** [comment]
Thank you for the feedback - it is appreciated. Tim:
Also, this is a good example c#/UWP snippet - appreciate your direction - Tim:

**Comment by twcarnahan** [comment]
I would like to inquire if you have a sample of this One Drive "sharing" link --- Many thanks, Tim:

**Comment by DianeD** [comment]
Here's the [docs](https://graph.microsoft.io/en-us/docs/api-reference/v1.0/api/item_createlink) that describe sharing links and options for creating and using them.

This [test snippet](https://github.com/microsoftgraph/msgraph-sdk-dotnet/blob/0fc7df3c2a0827d3ac2c2db68baf0e72029977e6/tests/Microsoft.Graph.Test/Requests/Functional/OneDriveTests.cs#L211) in the client library creates an **edit** sharing link using the item path. 

Or you can use the item id that's returned when you upload the file. This snippet uses the item id to create a **view** sharing link and then just gets the link URL from the returned Permission:

```
Permission permission = await graphClient.Me.Drive.Items[id].CreateLink("view").Request().PostAsync();
string url = permission.Link.WebUrl;
```

**Comment by DianeD** [comment]
Hi @twcarnahan . Closing this issue. Please reopen if you are still having problems. Thanks!
