### ISSUE TITLE
Sample is an Asp.net app but the app portal only supports  javascript

### ISSUE THREAD

**Issue by robvon** [microsoftgraph/aspnet-snippets-sample#24]
I don't use .Net core, I don't use Javascript, the sample is ASP.NET 4.6 - ie real .NET for microsoft developers.
The instructions send  you to the app portal which doesn't support microsoft products only IOS (not owned by microsoft), Android (ditto) and Javascript (wonderful scripting language also not microsoft).

This sample is thus  useless for its intended audience.

**Comment by jamescro** [comment]
What gives you the impression that the [App registration portal](https://apps.dev.microsoft.com) doesn't support Microsoft platforms and frameworks? I've registered clients for UWP, ASP.NET, and Xamarin in that portal (as well as for iOS, Android, and JS). Does the UI in the portal suggest that it supports only Android, iOS, and JS, or have you not had any success with clients registered on the portal?

**Comment by jamescro** [comment]
Closing for now. The app portal supports Microsoft frameworks. Please let us know of any specific problems you're having with the sample.
