### ISSUE TITLE
Error. An error occurred while processing your request.

### ISSUE THREAD

**Issue by JordaniRozon** [microsoftgraph/aspnet-snippets-sample#25]
I'm having this error when I click send email (I'm logged in with my personal account MSA). 

Error in /Mail/SendMessage: ErrorInvalidUser The requested user 'EMAIL' is invalid.

**Comment by jamescro** [comment]
What value appears in the email address box?

**Comment by jamescro** [comment]
Resolving for now. Let us know if this problem has persisted.
