### ISSUE TITLE
ASP .Net Core samples?

### ISSUE THREAD

**Issue by zemien** [microsoftgraph/aspnet-snippets-sample#26]
Hi, I'm having trouble converting the example app to ASP .Net Core because some of the libraries are different or do not exist. Is there a plan to create another sample project that's suitable for ASP .Net Core? I've managed to use app.UseOpenIdConnectAuthentication to connect to my workplace's Azure AD, but not sure how to make the next step into calling the Graph API?

**Comment by jamescro** [comment]
Have you seen this sample? 
https://github.com/microsoftgraph/aspnetcore-apponlytoken-webhooks-sample
It uses a different permissions model, and it does different operations with Graph, but it does show how to connect in an ASP.NET Core application.
We do want to publish more ASP.NET core samples. We're still prioritizing that work.

**Comment by zemien** [comment]
Thanks Jim! That sample should point me in the right direction.

**Comment by jamescro** [comment]
Thanks! I'm glad that helped.
