### ISSUE TITLE
Open/Schema Extensions Samples?

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/aspnet-snippets-sample#29]
The SDK now supports extensions, any plans to add to this sample application? (REST sample available at https://github.com/microsoftgraph/uwp-csharp-snippets-rest-sample) If PRs are welcome, I might take a look into this (ExtensionsService?).

**Comment by jamescro** [comment]
Thanks for the feedback. We would love to have extensions in this sample, but that work isn't currently scheduled. We are open to PRs, so please feel free to submit one if you have some snippets you'd like to contribute. Please follow the guidelines in this document: https://github.com/microsoftgraph/aspnet-snippets-sample/blob/master/CONTRIBUTING.md

**Comment by jamescro** [comment]
Thanks for your PR. Closing this now that we've established a process for adding extension snippets.
