### ISSUE TITLE
Helpers\SDKHelper.cs(14,43,14,54): warning CS0414: The field 'SDKHelper.graphClient' is assigned but its value is never used

### ISSUE THREAD

**Issue by christophwille** [microsoftgraph/aspnet-snippets-sample#30]
In preparing to start work on a PR, I noticed the warning. On looking at the SDKHelper, one can see what's causing the issue: a private field of the same name as a local variable (field being never really used, because SignOutClient() is never called). This should be cleaned up.

**Comment by jamescro** [comment]
Thanks for catching this. There is an issue like this in another ASP.NET sample. I'll take care of it after we're done with your PR.

**Comment by jamescro** [comment]
I've removed the unused graphClient object and the unused SignOutClient method.
