### ISSUE TITLE
TokenValidationParameters' is defined in System.IdentityModel.Token.Jwt but it could not be found.

### ISSUE THREAD

**Issue by Slowbat** [microsoftgraph/aspnet-snippets-sample#34]
Using the NuGet package System.IdentityModel.Tokens.Jwt 5.1.4. results in error message. 

TokenValidationParameters' is defined in System.IdentityModel.Token.Jwt but it could not be found in Startup.Auth.cs.

Using package 4.x seems to resolve that problem.

**Comment by jasonjoh** [comment]
S.I.T.J 5.x implemented a breaking change, and isn't compatible with the OWIN packages used by this sample. I'll be updating this to ASP.NET Core soon, so this will be a non-issue.
