### ISSUE TITLE
Get groups - Authorization_RequestDenied

### ISSUE THREAD

**Issue by humaflorin** [microsoftgraph/aspnet-snippets-sample#35]
Hi.

My question is: Only admin creator of Active Directory(AD) can read/write groups ?

With default AD members (with directory role = Global administrator) i can access users, but not groups.
https://prnt.sc/hxmp32

**Comment by jamescro** [comment]
Yes. You can refer to this document for a list of scopes: https://developer.microsoft.com/en-us/graph/docs/concepts/permissions_reference
This topic also indicates whether a scope requires admin consent, and unfortunately the current group-related scopes all require admin consent.
