### ISSUE TITLE
Question: How to get the group picture along with group properties

### ISSUE THREAD

**Issue by ymihir** [microsoftgraph/aspnet-snippets-sample#39]
I am able to retrieve all the required properties for all the group. To get the group image I have created another method. I am calling this method inside above all groups loop. Of course I am getting output and show the group name along with Image, but it is taking close to 20-25 secs since getGroupImage method is calling inside all groups loop. 
My actual question is how to get the group image along with the group properties. If I see in the [documentation](https://developer.microsoft.com/en-us/graph/docs/api-reference/v1.0/api/group_get) there is no property mentioned about group image. How to get the group properties along with image in single call?

**Comment by jasonjoh** [comment]
You can't. Photo requires a separate call.
