### ISSUE TITLE
Microsoft Graph is only for Azure AD?

### ISSUE THREAD

**Issue by Rod-in-NM** [microsoftgraph/aspnet-snippets-sample#41]
I've read through the README.md and some of the controller classes. I've used the older Azure AD Graph API. Microsoft Graph looks like what I should use, if I want to use Azure AD. But I've also got to be able to use ADFS. So, I'd like to ask a clarifying question, am I correct in believing that Microsoft Graph is _only_ for Azure AD?

**Comment by jasonjoh** [comment]
Microsoft Graph is only for accessing data in the cloud. That means either Azure AD users or personal Microsoft accounts (like live.com, outlook.com, etc.)
