### ISSUE TITLE
Where is the Resources resource?

### ISSUE THREAD

**Issue by Thedemtron** [microsoftgraph/aspnet-snippets-sample#43]
I am trying to use the example for MS Graph Member of function.  The example is the public class Groups Services.    It has a using Resources statement but I have no Idea where the dll is to reference in the references section.   

Please help.   cannot find many examples and I need to figure out all the groups the current is a member of.  The examples I do find are incomplete.  (They leave information out :( )

**Comment by uthpala1000** [comment]
just right click on the project and add -> new resource file. 
copy the content from the snippet project resource file and past
