### ISSUE TITLE
Microsoft.Identity.Web.MicrosoftGraphExtensions AddMicrosoftGraph extension

### ISSUE THREAD

**Issue by OlzhabaevSh** [microsoftgraph/aspnet-snippets-sample#60]
Greetings!

I have a problem with AddMicrosoftGraph extension (from Microsoft.Identity.Web namespace, MicrosoftGraphExtensions class). 

In tutorial you wrote about Microsoft.Identity.Web library with version 0.3-preview. 
In my case I try to use it in 1.1 version, so I can't find this method. 
Is this moved? And if yes where I can find it? 

Thank you

**Comment by jasonjoh** [comment]
Yes, they moved it into a separate package: Microsoft.Identity.Web.MicrosoftGraph

**Comment by OlzhabaevSh** [comment]
Ohhh... Thank you!

Should we update the source code and documentation? 

I mean it's a real useful information.

**Comment by jasonjoh** [comment]
Yes for sure. Now that M.I.W is officially released, I'll be updating this sample when I can.

**Comment by nikkh** [comment]
I didn't see any instruction to add nuget package for TimeZoneConverter?

**Comment by jasonjoh** [comment]
@nikkh this sample doesn't use that library.
