### ISSUE TITLE
Microsoft.Identity.Web v1.6.0 (IServiceCollection doesn't have AddSignIn)

### ISSUE THREAD

**Issue by dadrocker** [microsoftgraph/aspnet-snippets-sample#63]
After updating Identity.Web and Identity.Web.UI to any version after 0.1.5-preview, 
In startup.cs, ConfigureServices function fails for the reason of (IServiceCollection doesn't have AddSignIn).

**To Reproduce**

1. Update Microsoft.Identity.Web and Microsoft.Identity.Web.UI packages to any version above 0.1.5-preview
2. Build Project
3. See error

**Expected behavior**
Need implementation for especially adding the Microsoft.AspNetCore.Authentication.OpenIdConnect Events like OnAuthorizationCodeReceived, OnAuthenticationFailed,OnRemoteFailure

**Dependency versions**

 - Authentication library (MSAL, etc.) version: Same as last build
 - Graph library (Graph SDK, REST library, etc.) version:  **Microsoft.Graph, Version=3.6.0.0**

**Comment by jasonjoh** [comment]
Yeah, they seriously re-worked M.I.W before releasing it. You can see how it works at https://github.com/microsoftgraph/msgraph-training-aspnet-core. I'll be updating this sample to be in line with that sample shortly.
