### ISSUE TITLE
Calendar not working

### ISSUE THREAD

**Issue by oobhave** [microsoftgraph/aspnet-snippets-sample#67]
I am having trouble getting the Calendar section of this demo to work.

All other sections, Mail, Users, Groups, Teams and Files all ask for User authentication when selected the for first time. Calendar does not, it reports this instead:

Error getting calendar view
Code: generalException
Message: An error occurred sending the request.

I have tried adding Calender.ReadWrite to the API permissions for both Delegated and Application permissions but it makes no difference.

Any help or pointers appreciated.

**Comment by jasonjoh** [comment]
Thanks for reporting this @oobhave. The issue seems to be because the calendar controller is using it's own code to create the graph client rather than using the BaseController's method. I'll see if I can get a fix for this shortly.

**Comment by jasonjoh** [comment]
Try the updated code out and let me know if it doesn't work for you.

**Comment by oobhave** [comment]
Thank you for the speedy response and fix.

Works a treat!!!
