### ISSUE TITLE
Missing Areas?

### ISSUE THREAD

**Issue by philipstratford** [microsoftgraph/aspnet-snippets-sample#73]
This sample project has an anchor tag on the home page (`<a class="btn btn-primary btn-large" asp-area="MicrosoftIdentity" asp-controller="Account" asp-action="SignIn">Click here to sign in</a>`) which seems to point to an area named `MicrosoftIdentity`, but the project does not appear to contain any area definitions, and this link appears to point to nowhere.

**Comment by jasonjoh** [comment]
@philipstratford that area is added by the Microsoft.Identity.Web.UI package. Following that link should kick of the auth process (redirecting to login.microsoftonline.com).
